# Generated by Django 3.0.2 on 2020-01-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='bust',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='hips',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='shoe',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='waist',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
