# Generated by Django 3.0.2 on 2020-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200120_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='core.Job'),
        ),
    ]
