# Generated by Django 3.0.2 on 2020-01-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200123_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booker',
            name='agency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Agency'),
        ),
    ]
