# Generated by Django 3.0.2 on 2020-01-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200120_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='bookers',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='models',
        ),
        migrations.AddField(
            model_name='actor',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Agency'),
        ),
        migrations.AddField(
            model_name='booker',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Agency'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='eyes',
            field=models.CharField(choices=[('AMB', 'Amber'), ('BLU', 'Blue'), ('BRO', 'Brown'), ('GRA', 'Gray'), ('GRE', 'Green'), ('HAZ', 'Hazel')], max_length=3, null=True),
        ),
    ]
