# Generated by Django 3.0.2 on 2020-01-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200123_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booker',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Agency'),
        ),
        migrations.AlterField(
            model_name='booker',
            name='email',
            field=models.EmailField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booker',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Schedule'),
        ),
    ]
